### ISSUE TITLE
Dates parsing

### ISSUE THREAD

**Issue by paulinshek** [paulinshek/libraryapi#1]
Dates are incorrectly parsed in Reservation class.

Error:

```
{
  "timestamp": 1471425159149,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.http.converter.HttpMessageNotWritableException",
  "message": "Could not write content: formatter (through reference chain: library_project.models.Reservation[\"late\"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: formatter (through reference chain: library_project.models.Reservation[\"late\"])",
  "path": "/api/library/reservations"
}
```

Works when I make isLate always return `false` in https://github.com/paulinshek/libraryapi/blob/211369dcc012fd37b5067ac5177dd3fbe03fdc22/src/main/java/library_project/models/Reservation.java#L52

**Comment by dmorrisSL** [comment]
OK, that's a strange one.

I think that Jackson is trying to convert a field called 'formatter' to JSON, but the weird thing is that you don't have a field called 'formatter'.

Long shot: Did you rename 'formatter' to 'dateFormatter' between capturing the above JSON and posting this github issue?

**Comment by paulinshek** [comment]
No, dateFormatter has always been dateFormatter.

I thought it was trying to convert a field called 'late' into JSON, inferred from the isLate method (scroll to the end for `library_project.models.Reservation[\"late\"]`)
