### ISSUE TITLE
catch (SQLException sqlEx) { } // ignore

### ISSUE THREAD

**Issue by dmorrisSL** [paulinshek/libraryapi#11]
(More of a suggestion than anything)

Ignoring exceptions is usually bad, of course, but if you're finding in development you want to ignore it because you're not sure what to do yet, you might like to throw a RuntimeException() like this:

`catch (SQLException sqlEx) { 
   throw new RuntimeException(sqlEx);
}`

At least, then, the runtime exception will surface at the console and you'll see what happened.

RuntimeException doesn't need to be declared with 'throws' in the method signature.

**Comment by paulinshek** [comment]
Thanks for the suggestion! I will definitely keep it in mind in the future. Now that hibernate is being used, this does not apply anymore, so I'll close the issue. :)
