### ISSUE TITLE
Synchronisation issue in constructor

### ISSUE THREAD

**Issue by dmorrisSL** [paulinshek/libraryapi#4]
I think this code needs to be synchronized.

Two threads converging at this point might allocate the same reservationId, if they read the value of COUNT prior to incrementing it with COUNT++

https://github.com/paulinshek/libraryapi/blob/211369dcc012fd37b5067ac5177dd3fbe03fdc22/src/main/java/library_project/models/Reservation.java#L30

**Comment by paulinshek** [comment]
Indeed, thanks!
