### ISSUE TITLE
Capitalisation of static variables

### ISSUE THREAD

**Issue by dmorrisSL** [paulinshek/libraryapi#6]
It's a fairly widespread convention that only constant (i.e final static) are capitalised as variable names.

Even though COUNT it's static, it's not also 'final', so it would usually be just 'count'.

It's just a convention, but some compilers/IDEs or code checkers would grumble.

https://github.com/paulinshek/libraryapi/blob/211369dcc012fd37b5067ac5177dd3fbe03fdc22/src/main/java/library_project/models/Reservation.java#L22

**Comment by paulinshek** [comment]
Thanks!
